[profile.release]
panic = "unwind"

[workspace]
resolver = "2"

members = [
	"beefy-cli",
	"beefy-gadget",
	"beefy-gadget/rpc",
	"beefy-merkle-root",
	"beefy-node/node",
	"beefy-node/runtime",
	"beefy-pallet",
	"beefy-primitives",
	"beefy-test",
]
