[profile.release]
panic = "unwind"

[workspace]
members = [
	"beefy-gadget",
	"beefy-gadget/rpc",
	"beefy-pallet",
	"node-example/node",
	"node-example/pallets/template",
	"node-example/runtime",
	"primitives",
]
