[profile.release]
panic = "unwind"

[workspace]
resolver = "2"

members = [
    "beefy-cli",
    "beefy-gadget",
    "beefy-gadget/rpc",
    "beefy-merkle-tree",
    "beefy-node/node",
    "beefy-node/runtime",
    "beefy-pallet",
    "beefy-primitives",
    "beefy-mmr-pallet",
    "beefy-test",
]
