[package]
name = "beefy-gadget-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

[dependencies]
futures = { version = "0.3.12", features = ["compat"] }
log = "0.4"
serde = { version = "1.0.123", features = ["derive"] }
serde_json = "1.0.62"

jsonrpc-core = "15.1.0"
jsonrpc-core-client = "15.1.0"
jsonrpc-derive = "15.1.0"
jsonrpc-pubsub = "15.1.0"

codec = { version = "2.0.0", package = "parity-scale-codec", features = ["derive"] }

sc-rpc = { git = "https://github.com/paritytech/substrate", branch = "master" }

sp-core = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }

beefy-gadget = { path = "../." }
beefy-primitives = { path = "../../beefy-primitives" }
