name:                   Cargo deny

on:
  pull_request:
  schedule:
    - cron:             '0 0 * * *'
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
  cargo-deny:
    runs-on:            ubuntu-latest
    steps:
      - name:           Cancel Previous Runs
        uses:           styfle/cancel-workflow-action@bb6001c4ea612bf59c3abfc4756fbceee4f870c7 # 0.10.0
        with:
          access_token: ${{ github.token }}
      - name:           Checkout sources & submodules
        uses:           actions/checkout@v3
        with:
          fetch-depth:  5
          submodules:   recursive
      - name:           Cargo deny
        uses:           EmbarkStudios/cargo-deny-action@v1
        with:
          command:      "check --hide-inclusion-graph"
