name:                              Compilation and Testing Suite

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - 'README.md'
jobs:
  build:
    name:                          Build
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:   full
      NIGHTLY: nightly
    steps:
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # 0.10.0
        with:
          access_token:            ${{ github.token }}
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v3
        with:
          fetch-depth:             5
          submodules:              recursive
      - name:                      Install Toolchain
        run:                       rustup toolchain add $NIGHTLY
      - name:                      Add WASM Utilities
        run:                       rustup target add wasm32-unknown-unknown --toolchain $NIGHTLY
## Build Stage
      - name:                      Building rust-stable
        uses:                      actions-rs/cargo@v1
        if:                        github.ref == 'refs/heads/master'
        with:
          command:                 build
          toolchain:               stable
          args:                    --all --release --verbose

  check-test:
    name:                          Check and test
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:   full
      NIGHTLY: nightly
    steps:
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@b173b6ec0100793626c2d9e6b90435061f4fc3e5 # 0.10.0
        with:
          access_token:            ${{ github.token }}
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v3
        with:
          fetch-depth:             5
          submodules:              recursive
      - name:                      Install Toolchain
        run:                       rustup toolchain add $NIGHTLY
      - name:                      Add WASM Utilities
        run:                       rustup target add wasm32-unknown-unknown --toolchain $NIGHTLY
## Check Stage
      - name:                      Checking rust-stable
        uses:                      actions-rs/cargo@v1
        with:
          command:                 check
          toolchain:               stable
          args:                    --all  --verbose

## Test Stage
      - name:                      Testing rust-stable
        uses:                      actions-rs/cargo@v1
        with:
          command:                 test
          toolchain:               stable
          args:                    --all  --verbose
