name:                              Compilation and Testing Suite

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - v*
    paths-ignore:
      - '**.md'
      - docs/*
jobs:

## Check Stage
  check-test:
    name:                          Check and test
    strategy:
      matrix:
        toolchain:
          - stable
          #- beta
          - nightly
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:              full
      NIGHTLY:                     nightly #if necessary, specify the version, nightly-2020-10-04, etc.
    steps:
      
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}
      
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      
      - name:                      Install Toolchain
        run:                       rustup toolchain add $NIGHTLY
      
      - name:                      Add WASM Utilities
        run:                       rustup target add wasm32-unknown-unknown --toolchain $NIGHTLY
      
      - name:                      Checking rust-${{ matrix.toolchain }}
        uses:                      actions-rs/cargo@master
        with:
          command:                 check
          toolchain:               ${{ matrix.toolchain }}
          args:                    --all  --verbose

## Test Stage
      - name:                      Testing rust-${{ matrix.toolchain }}
        uses:                      actions-rs/cargo@master
        if:                        matrix.toolchain == 'stable'
        with:
          command:                 test
          toolchain:               ${{ matrix.toolchain }}
          args:                    --all  --verbose

## Build Stage
  build:
    name:                          Build
    strategy:
      matrix:
        toolchain:
          - stable
          #- beta
          - nightly
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:              full
      NIGHTLY:                     nightly #if necessary, specify the version, nightly-2020-10-04, etc.
    steps:
      
      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}
      
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      
      - name:                      Install Toolchain
        run:                       rustup toolchain add $NIGHTLY
      
      - name:                      Add WASM Utilities
        run:                       rustup target add wasm32-unknown-unknown --toolchain $NIGHTLY
      
      - name:                      Building rust-${{ matrix.toolchain }}
        uses:                      actions-rs/cargo@master
        if:                        github.ref == 'refs/heads/master'
        with:
          command:                 build
          toolchain:               ${{ matrix.toolchain }}
          args:                    --all --verbose
      
 ## Linting Stage
  clippy:
    name:                          Clippy
    runs-on:                       ubuntu-latest
    env:
      RUST_BACKTRACE:              full
      NIGHTLY:                     nightly #if necessary, specify the version, nightly-2020-10-04, etc.
    steps:

      - name:                      Cancel Previous Runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}
      
      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@master
        with:
          fetch-depth:             5
          submodules:              recursive
      
      - name:                      Install Toolchain
        run:                       rustup toolchain add $NIGHTLY
      
      - name:                      Add WASM Utilities
        run:                       rustup target add wasm32-unknown-unknown --toolchain $NIGHTLY
      
      - name:                      Add clippy
        run:                       rustup component add clippy --toolchain $NIGHTLY
            
      - name:                      Clippy
        uses:                      actions-rs/cargo@master
        with:
          command:                 clippy
          toolchain:               nightly #if necessary, specify the version, nightly-2020-10-04, etc.
          args:                    --all-targets -- -D warnings